export const SET_PLAY = "SET_PLAY";
export const SET_SHOW_SURVEY_POPUP = "SET_SHOW_SURVEY_POPUP";
export const ADD_CONTENT = "ADD_CONTENT";
export const ADD_CONTENT_FIRST_ORDER = "ADD_CONTENT_FIRST_ORDER";
export const DELETE_CONTENT = "DELETE_CONTENT";
